### PR TITLE
test: add PHP 8.2 & 8.3 to CI

### PR DESCRIPTION
**Pull request by jdecool**
## Description

Add test with PHP 8.2 & 8.3 in GitHub Actions

## Motivation and context

I want to use the library into a project and I want to ensure every things is OK with latest PHP version.

## How has this been tested?

It only impact the CI.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by hidehalo** [comment]
https://github.com/hidehalo/nanoid-php/actions/runs/8208653671/job/22493982806?pr=29
https://github.com/hidehalo/nanoid-php/actions/runs/8208653671/job/22494038119?pr=29
https://github.com/hidehalo/nanoid-php/actions/runs/8208653671/job/22494038198?pr=29

@jdecool here we are.

**Comment by hidehalo** [comment]
I create a new [issue](https://github.com/hidehalo/nanoid-php/issues/30) for this requirement.

**Comment by jdecool** [comment]
Just push a fix for those errors.

**Comment by hidehalo** [comment]
> Just push a fix for those errors.

@jdecool Thx for your help!

CI tests still failed

- PHP 8.1 https://github.com/hidehalo/nanoid-php/actions/runs/8228275524/job/22549165723?pr=29
- PHP 8.2 https://github.com/hidehalo/nanoid-php/actions/runs/8228275524/job/22549165920?pr=29
- PHP8.3 https://github.com/hidehalo/nanoid-php/actions/runs/8228275524/job/22549166069?pr=29

It seems PHPUnit configuration file need migrate on PHP 8.1 & 8.2 & 8.3.

We can migrate the stale configuration file first by following PHPUnit's instructions and then observe its backward compatibility & CI test results.

> Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"

**Comment by jdecool** [comment]
Just push an updated version of the PHPUnit configuration.

**Comment by hidehalo** [comment]
@jdecool Great job! Every things is OK now.

**Pull request merged**
